### ISSUE TITLE
Possibility to add a widget / extra icon to the chat bubble

### ISSUE THREAD

**Issue by bbence84** [prahack/chat_bubbles#14]
Hi!
This is a great package, thanks for developing it! :) I know my request might sound a bit too specific, but I need to add an additional icon next to the text that can be tapped. So the normal text + an IconButton next to the text (either on the right or left side) would be useful for me. Being able to provide a custom widget as content would also be OK. :)

Thanks!
Bence

**Comment by JohnF17** [comment]
🚀 #25
